spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/initializer_db
    username: lordran 
    password: lordranpass  
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update