spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tested
    username: londor  
    password: londorpass  
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update